# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iAgent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iAgent
  pod "Parse"
  pod "AlamofireImage"

  target 'iAgentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iAgentUITests' do
    # Pods for testing
  end

end
